
version: '3.1'

volumes:
  database-data:

services:
  pg_db:
    image: postgres
    restart: always
    env_file:
     - database.env
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - ${POSTGRES_PORT:-5432}:5432
  server:
    image: test
    environment:
      - PGPASS=ozon
      - PGUSER=ozon
      - PGADDR=pg_db/linker
    ports:
      -8080:8080
      -5432:5432
